import { sections } from '../public/assets/briefing-schema.mjs';
const escape = text => String(text).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
function renderField(q) {
  const attrs = `name="${q.id}" id="brief-${q.id}"${q.required ? ' required' : ''}${q.hint ? ` aria-describedby="hint-${q.id}"` : ''}`;
  const hint = q.hint ? `<span class="field-hint" id="hint-${q.id}">${escape(q.hint)}</span>` : '';
  if (q.type === 'checkbox') return `<label class="brief-check"><input type="checkbox" ${attrs}><span>${escape(q.label)} *</span></label>`;
  const control = q.type === 'textarea' ? `<textarea ${attrs} rows="4" maxlength="8000"></textarea>`
    : q.type === 'select' ? `<select ${attrs}><option value="">Selecione uma opção</option>${q.options.map(o => `<option>${escape(o)}</option>`).join('')}</select>`
      : `<input type="${q.type}" ${attrs} maxlength="8000"${q.type === 'text' ? ' autocomplete="off"' : ''}>`;
  return `<label for="brief-${q.id}">${escape(q.label)}${q.required ? ' *' : ''}${hint}${control}</label>`;
}
export function briefingPage() {
  return `<section class="dark compact-hero brief-hero"><div class="container"><p class="eyebrow">Seu projeto · Logos Data</p><h1>Vamos conhecer o seu site.</h1><p class="hero-copy">Cada resposta ajuda a transformar sua ideia em um projeto claro. Preencha no seu ritmo; quando não souber algo, indique isso no campo.</p></div></section><section class="brief-shell"><div class="container"><div id="brief-access" class="brief-notice" role="status">Conferindo seu link de acesso…</div><div class="brief-layout"><aside class="brief-sidebar"><p class="eyebrow">Seu briefing</p><ol id="brief-steps"></ol><p class="small">Campos com * são necessários. As outras respostas ajudam a personalizar o site.</p><button type="button" class="button secondary" id="save-draft">Salvar rascunho neste dispositivo</button><button type="button" class="text-link" id="load-draft">Retomar rascunho salvo</button><button type="button" class="text-link" id="clear-draft">Apagar rascunho deste dispositivo</button><p class="small">Os rascunhos só são salvos aqui quando você solicita. Use seu dispositivo pessoal.</p></aside><div><div class="brief-progress"><span id="brief-position"></span><progress id="brief-progress" max="100" value="0" aria-label="Etapas do briefing"></progress></div><form id="brief-form" novalidate>${sections.map((s, i) => `<fieldset class="brief-step" data-section="${s.id}"${i ? ' hidden' : ''}><legend>${escape(s.title)}</legend><p>${escape(s.intro)}</p>${s.fields.map(renderField).join('')}</fieldset>`).join('')}<fieldset class="brief-step" data-section="revisao" hidden><legend>Revise suas respostas</legend><p>Confira os dados antes de enviar. Nosso time usará estas respostas para organizar o conteúdo, identificar pendências e planejar o desenvolvimento do seu site.</p><div id="brief-review"></div><p class="small">Não inclua senhas ou informações que não sejam necessárias ao projeto. Materiais são enviados por links de pasta ou documento; confira as permissões de leitura.</p></fieldset><div class="brief-controls"><button type="button" class="button secondary" id="brief-back">Voltar</button><button type="button" class="button" id="brief-next">Continuar →</button><button type="submit" class="button" id="brief-submit" hidden>Enviar briefing</button></div><p id="brief-status" role="status" aria-live="polite"></p></form><button type="button" class="text-link" id="export-brief">Baixar cópia das respostas (JSON)</button></div></div></div></section><script type="module" src="/assets/briefing.js"></script>`;
}
export function checkoutPage() {
  return `<section class="dark compact-hero"><div class="container"><p class="eyebrow">Criação de site profissional</p><h1>Seu site começa aqui.</h1><p class="hero-copy">R$1.000 · Entrega em 14 dias. Pagamento por Pix ou cartão no checkout da InfinitePay.</p></div></section><section><div class="container quote-grid"><div><h2>Depois do pagamento</h2><p>Após a confirmação, você recebe por e-mail um link individual para preencher o briefing do site.</p><p>O briefing reúne sua identidade visual, serviços, textos, referências e materiais para orientar o desenvolvimento.</p><p class="small">Loja virtual, sistemas e integrações adicionais precisam de avaliação de escopo. Domínio e hospedagem são combinados separadamente.</p></div><form id="purchase-form"><label>Seu nome<input name="name" autocomplete="name" maxlength="120" required></label><label>E-mail para receber o formulário<input name="email" type="email" autocomplete="email" maxlength="160" required></label><label class="brief-check"><input type="checkbox" required><span>Conferi meu e-mail e entendi que receberei o formulário após a confirmação do pagamento.</span></label><button class="button" type="submit">Continuar para pagamento →</button><p id="purchase-status" role="status" aria-live="polite"></p></form></div></section><script type="module" src="/assets/checkout.js"></script>`;
}
export function paymentReturnPage() {
  return `<section class="dark compact-hero"><div class="container"><p class="eyebrow">Seu pedido · Logos Data</p><h1>Vamos conferir seu pagamento.</h1><p class="hero-copy" id="payment-status" role="status" aria-live="polite">Aguarde a confirmação da InfinitePay.</p><a class="button" href="/desenvolvimento-de-sites/">Voltar para o site</a></div></section><script type="module" src="/assets/payment-return.js"></script>`;
}
